version: "3.14"

services:
  # DJANGO ####################################################################
  app:
    image: zampo-server:latest
    container_name: "zampo-server"
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
      args:
        - DEV=true
    ports:
     - "8000:8000"
    volumes:
      - ./app:/app
    command: /start.sh
    env_file: ./.env/dev.env
    depends_on:
      - db
  # DATABASE ##################################################################
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file: ./.env/db.env

  # REDIS #####################################################################
  redis:
    container_name: "zampo-redis"
    image: redis:7-alpine
    restart: always
    depends_on:
      - db

  # CELERY ####################################################################
  worker:
    image: zampo-server:latest
    container_name: "zampo-worker"
    env_file:
      - ./.env/dev.env
    command: celery -A app worker -l INFO 
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - app
      - db
    restart: unless-stopped

  # CELERY BEAT ###############################################################
  scheduler:
    image: zampo-server:latest
    container_name: "zampo-scheduler"
    env_file:
      - ./.env/dev.env
    command: celery -A app beat -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - app
      - db
    restart: always

volumes:
  dev-db-data:
  static_volume:
  media_volume:
