version: "3.14"

services:
  # DJANGO ####################################################################
  app:
    image: zampo-server:latest
    container_name: "zampo-server"
    build:
      context: .
      dockerfile: docker/prod/Dockerfile 
    ports:
     - "8000:8000"
    volumes:
      - ./app/media_cdn/:/app/web/media_cdn/
      - ./app/static_cdn/:/app/static_cdn/
    command: /start.sh
    env_file: ./.env/prod.env

  # REDIS #####################################################################
  redis:
    container_name: "zampo-redis"
    image: redis:7-alpine
    restart: always

  # CELERY ####################################################################
  worker:
    image: zampo-server:latest
    container_name: "zampo-worker"
    env_file:
      - ./.env/prod.env
    command: celery -A app worker -l INFO  -f ./logs/celery.log
    volumes:
      - ./app/logs/:/app/logs/
    depends_on:
      - redis
      - app
    restart: unless-stopped

  # CELERY BEAT ###############################################################
  scheduler:
    image: zampo-server:latest
    container_name: "zampo-scheduler"
    env_file:
      - ./.env/prod.env
    command: celery -A app beat -l INFO -f ./logs/beat.log --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app/logs/:/app/logs/
    depends_on:
      - redis
      - app
    restart: always


