# Generated by Django 4.1.6 on 2023-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_username_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='username',
            field=models.TextField(default='Anonimo'),
        ),
    ]
