# Generated by Django 4.1.13 on 2023-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_pswd_reset',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
