# Generated by Django 4.1.13 on 2023-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_otp_pswd_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='age',
            new_name='age_max',
        ),
        migrations.AddField(
            model_name='post',
            name='age_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
